import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google';
import Nav from '@/components/Nav';
import Sidebar from '@/components/Sidebar';
const poppin = Poppins({
  weight: ['100', '400'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  authors: [{ name: "Sahan Ediriweera Charuka Samarakoon Anuradha Wickramasinghe" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppin.className}>
        <Nav />
        <Sidebar/>
        {children}
        </body>
    </html>
  )
}
