import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google';
import Nav from '@/components/Nav';
import Sidebar from '@/components/Sidebar';
import {Providers} from "./providers";
const poppin = Poppins({
  weight: ['100', '400'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  authors: [{ name: "Sahan Ediriweera Charuka Samarakoon Anuradha Wickramasinghe" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='dark'>
      <body className="bg-gray-100">
        <Providers>
        <div className="flex flex-col h-screen overflow-hidden">
          <Nav/>
          <div className="flex flex-1 overflow-y-auto p-5">
            <Sidebar/>
            <main className="w-3/4 p-4">{children}</main>
          </div>
        </div>
        </Providers>
      </body>
    </html>
  );
}
